# Generated by Django 4.1 on 2022-08-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
