name: Python application  

on: [push] 

jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyversion: ['3.8']
    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Contrasena22.
          POSTGRES_DB: TFG
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{matrix.pyversion}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.pyversion}}
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install codacy-coverage
    - name: Run migrations
      run: python manage.py makemigrations;python manage.py migrate;
  deploy:
    if: ${{github.ref == 'refs/heads/deploy'}} 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: echo "🔎 The name of your branch is ${{ github.ref }}."
    - uses: actions/checkout@v1
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
          heroku_app_name: "fantasytips"
          heroku_email: "jramosarrondo@gmail.com"
    - run: heroku run -a fantasytips sh -c "python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.filter(username='admin') or User.objects.create_superuser('admin', 'admin@example.com', 'admin')\""
